name: build & publish Docker image
on:
  push:
    tags:
      - '*'
jobs:
  docker-image:
    name: build & publish Docker image
    runs-on: ubuntu-latest
    steps:
    - name: parse Git tag
      id: git-tag
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: checkout
      uses: actions/checkout@v2

    - name: log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: build Docker image & push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          derhuerst/oxygen-xml:latest
          derhuerst/oxygen-xml:${{ steps.git-tag.outputs.tag }}
